"""Add compliance and bias monitoring tables

Revision ID: 0dedd8de254a
Revises: 002
Create Date: 2026-01-26 04:19:31.392752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dedd8de254a'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disparate_impact_reports',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('total_assessments', sa.Integer(), nullable=False),
    sa.Column('assessments_with_demographics', sa.Integer(), nullable=False),
    sa.Column('impact_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_disparate_impact', sa.Boolean(), nullable=False),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disparate_impact_reports_organization_id'), 'disparate_impact_reports', ['organization_id'], unique=False)
    op.create_table('candidate_demographics',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('race_ethnicity', sa.String(length=100), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('disability_status', sa.String(length=50), nullable=True),
    sa.Column('veteran_status', sa.String(length=50), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_text_shown', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_demographics_candidate_id'), 'candidate_demographics', ['candidate_id'], unique=True)
    op.create_table('rubric_validation_records',
    sa.Column('rubric_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitive_trait_weight_ratio', sa.Float(), nullable=True),
    sa.Column('job_relatedness_documented', sa.Boolean(), nullable=False),
    sa.Column('missing_documentation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_id'], ['scoring_rubrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_validation_records_organization_id'), 'rubric_validation_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rubric_validation_records_rubric_id'), 'rubric_validation_records', ['rubric_id'], unique=False)
    op.create_table('assessment_audit_records',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=False),
    sa.Column('role_profile_id', sa.UUID(), nullable=True),
    sa.Column('rubric_id', sa.UUID(), nullable=True),
    sa.Column('rubric_version', sa.String(length=50), nullable=True),
    sa.Column('rubric_source', sa.String(length=50), nullable=True),
    sa.Column('rubric_derivation_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trait_audit_records', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('recommendation_explanation', sa.Text(), nullable=True),
    sa.Column('protected_info_excluded', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_checks_passed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_profile_id'], ['role_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_id'], ['scoring_rubrics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_audit_records_assessment_id'), 'assessment_audit_records', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_audit_records_candidate_id'), 'assessment_audit_records', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessment_audit_records_interview_session_id'), 'assessment_audit_records', ['interview_session_id'], unique=False)
    op.create_table('candidate_disclosures',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('disclosure_type', sa.String(length=50), nullable=False),
    sa.Column('disclosure_version', sa.String(length=20), nullable=False),
    sa.Column('disclosure_content', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=True),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_disclosures_candidate_id'), 'candidate_disclosures', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_disclosures_interview_session_id'), 'candidate_disclosures', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_candidate_disclosures_organization_id'), 'candidate_disclosures', ['organization_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('interview_session_id', sa.UUID(), nullable=True),
    sa.Column('exchange_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('checked_content', sa.Text(), nullable=True),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_check_type'), 'compliance_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_compliance_checks_exchange_id'), 'compliance_checks', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_interview_session_id'), 'compliance_checks', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_organization_id'), 'compliance_checks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_checks_organization_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_interview_session_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_exchange_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_check_type'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_candidate_disclosures_organization_id'), table_name='candidate_disclosures')
    op.drop_index(op.f('ix_candidate_disclosures_interview_session_id'), table_name='candidate_disclosures')
    op.drop_index(op.f('ix_candidate_disclosures_candidate_id'), table_name='candidate_disclosures')
    op.drop_table('candidate_disclosures')
    op.drop_index(op.f('ix_assessment_audit_records_interview_session_id'), table_name='assessment_audit_records')
    op.drop_index(op.f('ix_assessment_audit_records_candidate_id'), table_name='assessment_audit_records')
    op.drop_index(op.f('ix_assessment_audit_records_assessment_id'), table_name='assessment_audit_records')
    op.drop_table('assessment_audit_records')
    op.drop_index(op.f('ix_rubric_validation_records_rubric_id'), table_name='rubric_validation_records')
    op.drop_index(op.f('ix_rubric_validation_records_organization_id'), table_name='rubric_validation_records')
    op.drop_table('rubric_validation_records')
    op.drop_index(op.f('ix_candidate_demographics_candidate_id'), table_name='candidate_demographics')
    op.drop_table('candidate_demographics')
    op.drop_index(op.f('ix_disparate_impact_reports_organization_id'), table_name='disparate_impact_reports')
    op.drop_table('disparate_impact_reports')
    # ### end Alembic commands ###
