"""add_invitations_table

Revision ID: 458cf442b0eb
Revises: 2f95b3dc2402
Create Date: 2026-01-26 06:49:50.013639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '458cf442b0eb'
down_revision: Union[str, None] = '2f95b3dc2402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invitation_type', sa.Enum('CANDIDATE_INTERVIEW', 'TOP_PERFORMER_PROFILING', name='invitationtype'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VIEWED', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('top_performer_id', sa.UUID(), nullable=True),
    sa.Column('interview_session_id', sa.UUID(), nullable=True),
    sa.Column('training_session_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('trait_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role_profile_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_profile_id'], ['role_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['top_performer_id'], ['top_performers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_candidate_id'), 'invitations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_invitations_invitation_type'), 'invitations', ['invitation_type'], unique=False)
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_top_performer_id'), 'invitations', ['top_performer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_top_performer_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invitation_type'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_candidate_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
