"""add_simple_mode_models

Revision ID: 54ed1e99f114
Revises: e222b6826761
Create Date: 2026-01-29 16:40:18.111911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54ed1e99f114'
down_revision: Union[str, None] = 'e222b6826761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='apikeytier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('requests_this_month', sa.Integer(), nullable=False),
    sa.Column('assessments_this_month', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_table('simple_assessments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('extracted_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements_confirmed', sa.Boolean(), nullable=False),
    sa.Column('requirements_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_trait_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REQUIREMENTS_PENDING', 'TRAITS_PENDING', 'CANDIDATES_PENDING', 'INTERVIEWING', 'COMPLETED', name='simpleassessmentstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('qualified_candidates', sa.Integer(), nullable=False),
    sa.Column('interviews_completed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_assessments_api_key_id'), 'simple_assessments', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_simple_assessments_organization_id'), 'simple_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_simple_assessments_status'), 'simple_assessments', ['status'], unique=False)
    op.create_table('simple_candidates',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_raw_text', sa.Text(), nullable=True),
    sa.Column('resume_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qualification_status', sa.Enum('PENDING', 'QUALIFIED', 'NOT_QUALIFIED', name='simplequalificationstatus'), nullable=False),
    sa.Column('qualification_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qualification_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('magic_link_token', sa.String(length=255), nullable=True),
    sa.Column('magic_link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_status', sa.Enum('NOT_STARTED', 'INVITED', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', name='simpleinterviewstatus'), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trait_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('recommendation_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['simple_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_candidates_assessment_id'), 'simple_candidates', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_simple_candidates_email'), 'simple_candidates', ['email'], unique=False)
    op.create_index(op.f('ix_simple_candidates_interview_status'), 'simple_candidates', ['interview_status'], unique=False)
    op.create_index(op.f('ix_simple_candidates_magic_link_token'), 'simple_candidates', ['magic_link_token'], unique=True)
    op.create_index(op.f('ix_simple_candidates_qualification_status'), 'simple_candidates', ['qualification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_candidates_qualification_status'), table_name='simple_candidates')
    op.drop_index(op.f('ix_simple_candidates_magic_link_token'), table_name='simple_candidates')
    op.drop_index(op.f('ix_simple_candidates_interview_status'), table_name='simple_candidates')
    op.drop_index(op.f('ix_simple_candidates_email'), table_name='simple_candidates')
    op.drop_index(op.f('ix_simple_candidates_assessment_id'), table_name='simple_candidates')
    op.drop_table('simple_candidates')
    op.drop_index(op.f('ix_simple_assessments_status'), table_name='simple_assessments')
    op.drop_index(op.f('ix_simple_assessments_organization_id'), table_name='simple_assessments')
    op.drop_index(op.f('ix_simple_assessments_api_key_id'), table_name='simple_assessments')
    op.drop_table('simple_assessments')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
