"""Make candidate_id nullable and add simple_candidate_id to interview_sessions

Revision ID: 6d5c095e925a
Revises: 54ed1e99f114
Create Date: 2026-01-29 19:12:39.414285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5c095e925a'
down_revision: Union[str, None] = '54ed1e99f114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_job_screening', 'candidate_job_screenings', type_='unique')
    op.add_column('interview_sessions', sa.Column('simple_candidate_id', sa.UUID(), nullable=True))
    op.alter_column('interview_sessions', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_interview_sessions_simple_candidate_id'), 'interview_sessions', ['simple_candidate_id'], unique=False)
    op.create_foreign_key(None, 'interview_sessions', 'simple_candidates', ['simple_candidate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_sessions_simple_candidate_id'), table_name='interview_sessions')
    op.alter_column('interview_sessions', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('interview_sessions', 'simple_candidate_id')
    op.create_unique_constraint('uq_candidate_job_screening', 'candidate_job_screenings', ['candidate_id', 'job_id'])
    # ### end Alembic commands ###
